name: custom_list_view_all_videos_of_specific_chapter
description: a custom list view package for all videos of specific chapter page of lecture progress app


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  custom_highly_reusable_functions:
    path: ../../../HighlyReusableFunctions
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


