name: custom_AWSApi_lecture_progress_app
description: a database package for database of lecture progress app


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sqflite: ^2.0.0+3
  flutter:
    sdk: flutter
  

  http: ^0.13.3




  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


